### ISSUE TITLE
[Suggestion] Don't use a template.

### ISSUE THREAD

**Issue by ParadoxZero** [RITct/ritct.github.io#3]
Instead use your own design, it will teach you a lot.
Templates are good when you want to set up a good looking website fast. But when the aim is learning web development. Start from scratch.

- Decide on the website structure first.
    - The number of pages.
    - The content on the pages
- Decide on a design.
    - Create some preliminary designs on paper
- Split the development into tasks using the designs
- Everyone perform different tasks and learn to collaborate.

**Comment by GopikrishnanSasikumar** [comment]
Use reacts,my suggestion

**Comment by gksoriginals** [comment]
use reactjs,my suggestion

**Comment by gautamkrishnar** [comment]
@Abhi1401 @Poirot1729  please remove all the old files from the repo if needed. I tried to bootstrap a website using https://github.com/netlify/victor-hugo

**Comment by abhishek-mvr** [comment]
I also don't appreciate using templates. We can use CSS and JS libraries.
Its a static site right ? 
We shall grab components from all over. ;)

**Comment by ebeyabraham** [comment]
I don't think anyone is going to make the design any soon. If someone who has experience with we designing just designs the main page we can atleast get everyone started.

**Comment by ParadoxZero** [comment]
@Poirot1729 Try and make a design on paper. Like draw out using pen and paper how the website should look like.

**Comment by ebeyabraham** [comment]
@ParadoxZero I don't think I'm the best person to do that, but will still give it a try. Will try to come up with one by tomorrow.

**Comment by ParadoxZero** [comment]
@Poirot1729 did you make it yet?

**Comment by ebeyabraham** [comment]
I'm sorry, I couldn't make it. A bit busy with my internship.

**Comment by ParadoxZero** [comment]
@Poirot1729 thats okay. Take your time.

**Comment by ebeyabraham** [comment]
![14984832530691280773658](https://user-images.githubusercontent.com/15849927/27541159-83fcc2e2-5aa0-11e7-92a6-27bb6b3a4cf5.jpg)
@ParadoxZero I hope this is what you meant. 
@gautamkrishnar @GopikrishnanSasikumar @Abhi1401 @gintu

**Comment by ebeyabraham** [comment]
Is it okay to move on with this :expressionless:

**Comment by ParadoxZero** [comment]
Well, I assumed that’s what a thumbs up meant xD

Sure go ahead with it.

**Comment by ebeyabraham** [comment]
Prefer words over emojis :joy:

**Comment by gautamkrishnar** [comment]
LGTM :+1:
We must add a separate page called **team** for listing org members...
